excluded:
- Pods
- iCarousel.m

# implicitly
line_length: 210
large_tuple: 4
function_body_length: 100
function_parameter_count: 20
type_body_length: 500
cyclomatic_complexity: 15
type_name: 50
file_length: 500
identifier_name: 2

disabled_rules:
  - trailing_whitespace
  - unneeded_override
