//
//  CitiesList.swift
//  Copilot
//
//  Created by Jamal on 3/14/24.
//

import Foundation

struct TurkeyCity {
    let name: String
    let code: String
}

var turkeyCitiesList = [
    TurkeyCity(name: "İstanbul", code: "34"),
    TurkeyCity(name: "Ankara", code: "06"),
    TurkeyCity(name: "İzmir", code: "35"),
    TurkeyCity(name: "Adana", code: "01"),
    TurkeyCity(name: "Adıyaman", code: "02"),
    TurkeyCity(name: "Afyon", code: "03"),
    TurkeyCity(name: "Ağrı", code: "04"),
    TurkeyCity(name: "Amasya", code: "05"),
    TurkeyCity(name: "Antalya", code: "07"),
    TurkeyCity(name: "Artvin", code: "08"),
    TurkeyCity(name: "Aydın", code: "09"),
    TurkeyCity(name: "Balıkesir", code: "10"),
    TurkeyCity(name: "Bilecik", code: "11"),
    TurkeyCity(name: "Bingöl", code: "12"),
    TurkeyCity(name: "Bitlis", code: "13"),
    TurkeyCity(name: "Bolu", code: "14"),
    TurkeyCity(name: "Burdur", code: "15"),
    TurkeyCity(name: "Bursa", code: "16"),
    TurkeyCity(name: "Çanakkale", code: "17"),
    TurkeyCity(name: "Çankırı", code: "18"),
    TurkeyCity(name: "Çorum", code: "19"),
    TurkeyCity(name: "Denizli", code: "20"),
    TurkeyCity(name: "Diyarbakır", code: "21"),
    TurkeyCity(name: "Edirne", code: "22"),
    TurkeyCity(name: "Elazığ", code: "23"),
    TurkeyCity(name: "Erzincan", code: "24"),
    TurkeyCity(name: "Erzurum", code: "25"),
    TurkeyCity(name: "Eskişehir", code: "26"),
    TurkeyCity(name: "Gaziantep", code: "27"),
    TurkeyCity(name: "Giresun", code: "28"),
    TurkeyCity(name: "Gümüşhane", code: "29"),
    TurkeyCity(name: "Hakkari", code: "30"),
    TurkeyCity(name: "Hatay", code: "31"),
    TurkeyCity(name: "Isparta", code: "32"),
    TurkeyCity(name: "Mersin", code: "33"),
    TurkeyCity(name: "Kars", code: "36"),
    TurkeyCity(name: "Kastamonu", code: "37"),
    TurkeyCity(name: "Kayseri", code: "38"),
    TurkeyCity(name: "Kırklareli", code: "39"),
    TurkeyCity(name: "Kırşehir", code: "40"),
    TurkeyCity(name: "Kocaeli", code: "41"),
    TurkeyCity(name: "Konya", code: "42"),
    TurkeyCity(name: "Kütahya", code: "43"),
    TurkeyCity(name: "Malatya", code: "44"),
    TurkeyCity(name: "Manisa", code: "45"),
    TurkeyCity(name: "Kahramanmaraş", code: "46"),
    TurkeyCity(name: "Mardin", code: "47"),
    TurkeyCity(name: "Muğla", code: "48"),
    TurkeyCity(name: "Muş", code: "49"),
    TurkeyCity(name: "Nevşehir", code: "50"),
    TurkeyCity(name: "Niğde", code: "51"),
    TurkeyCity(name: "Ordu", code: "52"),
    TurkeyCity(name: "Rize", code: "53"),
    TurkeyCity(name: "Sakarya", code: "54"),
    TurkeyCity(name: "Samsun", code: "55"),
    TurkeyCity(name: "Siirt", code: "56"),
    TurkeyCity(name: "Sinop", code: "57"),
    TurkeyCity(name: "Sivas", code: "58"),
    TurkeyCity(name: "Tekirdağ", code: "59"),
    TurkeyCity(name: "Tokat", code: "60"),
    TurkeyCity(name: "Trabzon", code: "61"),
    TurkeyCity(name: "Tunceli", code: "62"),
    TurkeyCity(name: "Şanlıurfa", code: "63"),
    TurkeyCity(name: "Uşak", code: "64"),
    TurkeyCity(name: "Van", code: "65"),
    TurkeyCity(name: "Yozgat", code: "66"),
    TurkeyCity(name: "Zonguldak", code: "67"),
    TurkeyCity(name: "Aksaray", code: "68"),
    TurkeyCity(name: "Bayburt", code: "69"),
    TurkeyCity(name: "Karaman", code: "70"),
    TurkeyCity(name: "Kırıkkale", code: "71"),
    TurkeyCity(name: "Batman", code: "72"),
    TurkeyCity(name: "Şırnak", code: "73"),
    TurkeyCity(name: "Bartın", code: "74"),
    TurkeyCity(name: "Ardahan", code: "75"),
    TurkeyCity(name: "Iğdır", code: "76"),
    TurkeyCity(name: "Yalova", code: "77"),
    TurkeyCity(name: "Karabük", code: "78"),
    TurkeyCity(name: "Kilis", code: "79"),
    TurkeyCity(name: "Osmaniye", code: "80"),
    TurkeyCity(name: "Düzce", code: "81")
]
